### ISSUE TITLE
without token and still able to retrieve

### ISSUE THREAD

**Issue by weihan1394** [hendisantika/spring-boot-security-oauth2-example#2]
When I try to perform the get method without providing the token, I am still able to access the data from the get method.
![capture](https://user-images.githubusercontent.com/7189650/42196783-40df6186-7eb2-11e8-8a24-3db8cc453dae.PNG)

**Comment by hendisantika** [comment]
Sorry for late response, @weihan1394 .
I didn't see any issue from this repo.

But, in my local side I can't get access `/users/user` endpoint without `access token`.

Can You check and run again?

Thanks

**Comment by hendisantika** [comment]
If there's no feed back, I will close this issue then, @weihan1394 .
