### ISSUE TITLE
getting 401 while hitting token api

### ISSUE THREAD

**Issue by snehadabriwal** [hendisantika/spring-boot-security-oauth2-example#3]
I imported the project and tried to access through postman and getting 401
{
    "timestamp": 1539835766505,
    "status": 401,
    "error": "Unauthorized",
    "message": "Bad credentials",
    "path": "/oauth/token"
}

**Comment by hendisantika** [comment]
Can You check again the screenshot that I have given in README, @snehadabriwal ?

Because in my side is it OK. No issue. Just checked again this morning still no Issue.

Thanks.

**Comment by hendisantika** [comment]
If there's no feed back, I will close this issue then.
