### ISSUE TITLE
spring upgrade to 2.0.17.RELEASE

### ISSUE THREAD

**Issue by gopuravi** [hendisantika/spring-boot-security-oauth2-example#4]
HI Hendisantika,
I'm new to spring security. Thanks for your code it works perfectly fine for spring version  - 1.5.21.RELEASE. When i update the spring version to 2.1.2.RELEASE. I'm getting unauthorized error.

The ouath version is 2.0.17.RELEASE. Any idea what i should do to fix the error

**Comment by hendisantika** [comment]
Hi @gopuravi , thank for your attention.

For Now just use Spring Boot 1.5.20.RELEASE Version.

I tested. Its OK if You are using that version.

But, If You upgraded into Spring Boot 2.2.0.RELEASE version it come with modification.

I tested. Many modification there.

I will update the code after all my repo has updated into latest Spring Boot version.

**Comment by hendisantika** [comment]
Case closed ya.
