### ISSUE TITLE
Multiple annotations found

### ISSUE THREAD

**Issue by gokulupadhyay** [hendisantika/spring-boot-security-oauth2-example#6]
Multiple annotations found at this line:
	- Project build error: Non-resolvable parent POM for com.hendisantika:spring-boot-security-
	 oauth2-example:1.0-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-starter-
	 parent:pom:2.8.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution 
	 will not be reattempted until the update interval of central has elapsed or updates are forced and 
	 'parent.relativePath' points at wrong local POM
	- Non-resolvable parent POM for com.hendisantika:spring-boot-security-oauth2-example:1.0-
	 SNAPSHOT: Could not find artifact org.springframework.boot:spring-boot-starter-parent:pom:2.8.0 in 
	 central (https://repo.maven.apache.org/maven2)

**Comment by hendisantika** [comment]
Can You pull latest code @gokulupadhyay ?
